sampling_rate: !!int 24000
fft_size: !!int 1024
hop_size: !!int 240
win_length: !!int 1024
window: hann
num_mels: !!int 80
fmin: !!int 0
fmax: !!int 8000
mel_min: !!float -12.0
mel_max: !!float 2.5
f0_floor: !!float 20.0
f0_ceil: !!float 600.0
