# experiment
dataset: vctk
train_meta: data/vctk/train_nodev_all/metadata.csv
dev_meta: data/vctk/dev_all/metadata.csv
train_set: train_nodev_all
dev_set: dev_all


# encoder-decoder
ling_enc: conformer_ppg
spk_enc: utt_dvec
pros_enc: ppgvc_f0
decoder: TacoMOL
mel_type: ppgvc_mel
vocoder: ppgvc_hifigan


# training 
fp16_run: !!bool True
epochs: 200
save_freq: 2 # save ckpt frequency
show_freq: 10
load_only_params: !!bool False
seed: !!int 1234
trainer: TacoMOLTrainer
ngpu: 2

#dataloader
dataset_class: Dataset
sort: !!bool True
dump_dir: dump
num_workers: !!int 8
batch_size: 32
drop_last: !!bool True
rm_long_utt: !!bool True # remove too long utterances from metadata
max_utt_duration: !!float 10.0 # max utterance duration (seconds)
frames_per_step: !!int 4


# decoder params
decoder_params: 
    prosodic_rep_type: continuous
    prosodic_net:
        hidden_dim: 256
    spk_embed_dim: 256
    bottle_neck_feature_dim: 144

#optimizer & scheduler
optimizer:
    weight_decay: !!float 1e-6
    betas: [0.9,0.99]  
    lr: !!float 1e-4
scheduler:    
    num_training_steps: 500000
    num_warmup_steps: 4000

# loss hyper-parameters
losses:
   alpha: 1. 
    






