# experiment
dataset: vctk
train_meta: data/vctk/train_nodev_all/metadata.csv
dev_meta: data/vctk/dev_all/metadata.csv
train_set: train_nodev_all
dev_set: dev_all


# encoder-decoder
ling_enc: whisper_ppg_small
spk_enc: utt_ecapa_tdnn
pros_enc: norm_fastspeech2_pitch_energy
decoder: DiffWave
mel_type: vits_spec # will not use it 
pros_stats: dump/vctk/train_nodev_all/fastspeech2_pitch_energy/train_nodev_all.npy

# training 
fp16_run: !!bool False
epochs: 2000
save_freq: 1 # save ckpt frequency
show_freq: 100 # show training information frequency
load_only_params: !!bool False
seed: !!int 1234
trainer: DiffWaveTrainer
ngpu: 1

#dataloader
dataset_class: VITSDataset
sampling_rate: !!int 24000
vits_hop_size: !!int 240
spec_max_len: !!int 60
sort: !!bool False
dump_dir: dump
num_workers: !!int 8
batch_size: 16
drop_last: !!bool True
rm_long_utt: !!bool False # remove too long utterances from metadata
max_utt_duration: !!float 10.0 # max utterance duration (seconds)


# decoder params
decoder_params: 
    segment_size: 14400 
    input_dim: !!int 768
    spk_emb_dim: !!int  192
    prosodic_rep_type: discrete
    prosodic_net:
        hidden_dim: 64
        prosodic_bins: !!int 256
        prosodic_stats_path: dump/vctk/train_nodev_all/fastspeech2_pitch_energy/pitch_energy_min_max.npy
    inter_channels: !!int 64
    hidden_channels: !!int 64
    filter_channels: !!int 128
    n_heads: !!int 2
    n_layers: !!int 6
    kernel_size: !!int 3
    p_dropout: !!float 0.1
    residual_channels: 64
    residual_layers: 30
    dilation_cycle_length: 10

    

#optimizer & scheduler
optimizer:
    lr: !!float 2e-4

# loss hyper-parameters
losses:
   alpha: 1. 
    






